export { Users } from "./Users.Routes";
export { Admin } from "./Admin.Routes";
export { Updation } from "./Updation.Routes";
export {Conference} from "./Conference.Routes";
export {Journal} from "./Journal.Routes";
export {Fdp} from "./Fdp.Routes";
export {Sttp} from "./Sttp.Routes";
export {Mrg} from "./Mrg.Routes";
export {Progatt} from "./Progatt.Routes";
export {Semwork} from "./Semwork.Routes";
